version: '3'
services:
  bot:
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGO_URI=${MONGO_URI}
      - GOOGLE_SHEET_WEBHOOK=${GOOGLE_SHEET_WEBHOOK}